//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcodexIntegrationSample.SrvCancelacion {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ListaCancelar", Namespace="http://Ecodex.WS.Model/2011/CFDI", ItemName="guid")]
    [System.SerializableAttribute()]
    public class ListaCancelar : System.Collections.Generic.List<System.Guid> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ListaResultadoCancelacion", Namespace="http://Ecodex.WS.Model/2011/CFDI", ItemName="ResultadoCancelacion")]
    [System.SerializableAttribute()]
    public class ListaResultadoCancelacion : System.Collections.Generic.List<EcodexIntegrationSample.SrvCancelacion.ResultadoCancelacion> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultadoCancelacion", Namespace="http://Ecodex.WS.Model/2011/CFDI")]
    [System.SerializableAttribute()]
    public partial class ResultadoCancelacion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid UUIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid UUID {
            get {
                return this.UUIDField;
            }
            set {
                if ((this.UUIDField.Equals(value) != true)) {
                    this.UUIDField = value;
                    this.RaisePropertyChanged("UUID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string Estatus {
            get {
                return this.EstatusField;
            }
            set {
                if ((object.ReferenceEquals(this.EstatusField, value) != true)) {
                    this.EstatusField = value;
                    this.RaisePropertyChanged("Estatus");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FallaSesion", Namespace="http://Ecodex.WS.Model/2011/CFDI")]
    [System.SerializableAttribute()]
    public partial class FallaSesion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string RFCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EstatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string RFC {
            get {
                return this.RFCField;
            }
            set {
                if ((object.ReferenceEquals(this.RFCField, value) != true)) {
                    this.RFCField = value;
                    this.RaisePropertyChanged("RFC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int Estatus {
            get {
                return this.EstatusField;
            }
            set {
                if ((this.EstatusField.Equals(value) != true)) {
                    this.EstatusField = value;
                    this.RaisePropertyChanged("Estatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FallaServicio", Namespace="http://Ecodex.WS.Model/2011/CFDI")]
    [System.SerializableAttribute()]
    public partial class FallaServicio : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string RFCField;
        
        private int NumeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EventoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string RFC {
            get {
                return this.RFCField;
            }
            set {
                if ((object.ReferenceEquals(this.RFCField, value) != true)) {
                    this.RFCField = value;
                    this.RaisePropertyChanged("RFC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int Numero {
            get {
                return this.NumeroField;
            }
            set {
                if ((this.NumeroField.Equals(value) != true)) {
                    this.NumeroField = value;
                    this.RaisePropertyChanged("Numero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string Evento {
            get {
                return this.EventoField;
            }
            set {
                if ((object.ReferenceEquals(this.EventoField, value) != true)) {
                    this.EventoField = value;
                    this.RaisePropertyChanged("Evento");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FallaValidacion", Namespace="http://Ecodex.WS.Model/2011/CFDI")]
    [System.SerializableAttribute()]
    public partial class FallaValidacion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string RFCField;
        
        private int NumeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NodoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AntecedenteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SugerenciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EventoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string RFC {
            get {
                return this.RFCField;
            }
            set {
                if ((object.ReferenceEquals(this.RFCField, value) != true)) {
                    this.RFCField = value;
                    this.RaisePropertyChanged("RFC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int Numero {
            get {
                return this.NumeroField;
            }
            set {
                if ((this.NumeroField.Equals(value) != true)) {
                    this.NumeroField = value;
                    this.RaisePropertyChanged("Numero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string Nodo {
            get {
                return this.NodoField;
            }
            set {
                if ((object.ReferenceEquals(this.NodoField, value) != true)) {
                    this.NodoField = value;
                    this.RaisePropertyChanged("Nodo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string Antecedente {
            get {
                return this.AntecedenteField;
            }
            set {
                if ((object.ReferenceEquals(this.AntecedenteField, value) != true)) {
                    this.AntecedenteField = value;
                    this.RaisePropertyChanged("Antecedente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string Sugerencia {
            get {
                return this.SugerenciaField;
            }
            set {
                if ((object.ReferenceEquals(this.SugerenciaField, value) != true)) {
                    this.SugerenciaField = value;
                    this.RaisePropertyChanged("Sugerencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string Evento {
            get {
                return this.EventoField;
            }
            set {
                if ((object.ReferenceEquals(this.EventoField, value) != true)) {
                    this.EventoField = value;
                    this.RaisePropertyChanged("Evento");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", ConfigurationName="SrvCancelacion.Cancelaciones")]
    public interface Cancelaciones {
        
        // CODEGEN: Generating message contract since the wrapper name (SolicitudCancelaMultiple) of message SolicitudCancelaMultiple does not match the default value (CancelaMultiple)
        [System.ServiceModel.OperationContractAttribute(Action="http://Ecodex.WS.Model/2011/CFDI/Cancelaciones/CancelaMultiple", ReplyAction="http://Ecodex.WS.Model/2011/CFDI/Cancelaciones/CancelaMultipleResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EcodexIntegrationSample.SrvCancelacion.FallaSesion), Action="http://Ecodex.WS.Model/2011/CFDI/Cancelaciones/CancelaMultipleFallaSesionFault", Name="FallaSesion")]
        [System.ServiceModel.FaultContractAttribute(typeof(EcodexIntegrationSample.SrvCancelacion.FallaServicio), Action="http://Ecodex.WS.Model/2011/CFDI/Cancelaciones/CancelaMultipleFallaServicioFault", Name="FallaServicio")]
        EcodexIntegrationSample.SrvCancelacion.RespuestaCancelaMultiple CancelaMultiple(EcodexIntegrationSample.SrvCancelacion.SolicitudCancelaMultiple request);
        
        // CODEGEN: Generating message contract since the wrapper name (SolicitudAcuse) of message SolicitudAcuse does not match the default value (RecuperarAcuses)
        [System.ServiceModel.OperationContractAttribute(Action="http://Ecodex.WS.Model/2011/CFDI/Cancelaciones/RecuperarAcuses", ReplyAction="http://Ecodex.WS.Model/2011/CFDI/Cancelaciones/RecuperarAcusesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EcodexIntegrationSample.SrvCancelacion.FallaValidacion), Action="http://Ecodex.WS.Model/2011/CFDI/Cancelaciones/RecuperarAcusesFallaValidacionFaul" +
            "t", Name="FallaValidacion")]
        [System.ServiceModel.FaultContractAttribute(typeof(EcodexIntegrationSample.SrvCancelacion.FallaSesion), Action="http://Ecodex.WS.Model/2011/CFDI/Cancelaciones/RecuperarAcusesFallaSesionFault", Name="FallaSesion")]
        [System.ServiceModel.FaultContractAttribute(typeof(EcodexIntegrationSample.SrvCancelacion.FallaServicio), Action="http://Ecodex.WS.Model/2011/CFDI/Cancelaciones/RecuperarAcusesFallaServicioFault", Name="FallaServicio")]
        EcodexIntegrationSample.SrvCancelacion.RespuestaRecuperarAcuse RecuperarAcuses(EcodexIntegrationSample.SrvCancelacion.SolicitudAcuse request);
        
        // CODEGEN: Generating message contract since the wrapper name (SolicitudCancelaOtros) of message SolicitudCancelaOtros does not match the default value (CancelaOtros)
        [System.ServiceModel.OperationContractAttribute(Action="http://Ecodex.WS.Model/2011/CFDI/Cancelaciones/CancelaOtros", ReplyAction="http://Ecodex.WS.Model/2011/CFDI/Cancelaciones/CancelaOtrosResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EcodexIntegrationSample.SrvCancelacion.FallaValidacion), Action="http://Ecodex.WS.Model/2011/CFDI/Cancelaciones/CancelaOtrosFallaValidacionFault", Name="FallaValidacion")]
        [System.ServiceModel.FaultContractAttribute(typeof(EcodexIntegrationSample.SrvCancelacion.FallaSesion), Action="http://Ecodex.WS.Model/2011/CFDI/Cancelaciones/CancelaOtrosFallaSesionFault", Name="FallaSesion")]
        [System.ServiceModel.FaultContractAttribute(typeof(EcodexIntegrationSample.SrvCancelacion.FallaServicio), Action="http://Ecodex.WS.Model/2011/CFDI/Cancelaciones/CancelaOtrosFallaServicioFault", Name="FallaServicio")]
        EcodexIntegrationSample.SrvCancelacion.RespuestaCancelaOtros CancelaOtros(EcodexIntegrationSample.SrvCancelacion.SolicitudCancelaOtros request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SolicitudCancelaMultiple", WrapperNamespace="http://Ecodex.WS.Model/2011/CFDI", IsWrapped=true)]
    public partial class SolicitudCancelaMultiple {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=0)]
        public EcodexIntegrationSample.SrvCancelacion.ListaCancelar ListaCancelar;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=1)]
        public string RFC;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=2)]
        public string Token;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=3)]
        public long TransaccionID;
        
        public SolicitudCancelaMultiple() {
        }
        
        public SolicitudCancelaMultiple(EcodexIntegrationSample.SrvCancelacion.ListaCancelar ListaCancelar, string RFC, string Token, long TransaccionID) {
            this.ListaCancelar = ListaCancelar;
            this.RFC = RFC;
            this.Token = Token;
            this.TransaccionID = TransaccionID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RespuestaCancelaMultiple", WrapperNamespace="http://Ecodex.WS.Model/2011/CFDI", IsWrapped=true)]
    public partial class RespuestaCancelaMultiple {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=0)]
        public EcodexIntegrationSample.SrvCancelacion.ListaResultadoCancelacion Resultado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=1)]
        public string TransaccionID;
        
        public RespuestaCancelaMultiple() {
        }
        
        public RespuestaCancelaMultiple(EcodexIntegrationSample.SrvCancelacion.ListaResultadoCancelacion Resultado, string TransaccionID) {
            this.Resultado = Resultado;
            this.TransaccionID = TransaccionID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SolicitudAcuse", WrapperNamespace="http://Ecodex.WS.Model/2011/CFDI", IsWrapped=true)]
    public partial class SolicitudAcuse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=0)]
        public string RFC;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=1)]
        public string Token;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=2)]
        public long TransaccionID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=3)]
        public System.Guid UUID;
        
        public SolicitudAcuse() {
        }
        
        public SolicitudAcuse(string RFC, string Token, long TransaccionID, System.Guid UUID) {
            this.RFC = RFC;
            this.Token = Token;
            this.TransaccionID = TransaccionID;
            this.UUID = UUID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RespuestaRecuperarAcuse", WrapperNamespace="http://Ecodex.WS.Model/2011/CFDI", IsWrapped=true)]
    public partial class RespuestaRecuperarAcuse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=0)]
        public string AcuseXML;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=1)]
        public string Estatus;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=2)]
        public long TransaccionID;
        
        public RespuestaRecuperarAcuse() {
        }
        
        public RespuestaRecuperarAcuse(string AcuseXML, string Estatus, long TransaccionID) {
            this.AcuseXML = AcuseXML;
            this.Estatus = Estatus;
            this.TransaccionID = TransaccionID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SolicitudCancelaOtros", WrapperNamespace="http://Ecodex.WS.Model/2011/CFDI", IsWrapped=true)]
    public partial class SolicitudCancelaOtros {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=0)]
        public string RFCEmisor;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=1)]
        public string RFCReceptor;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=2)]
        public string Token;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=3)]
        public long TransaccionID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=4)]
        public System.Guid UUID;
        
        public SolicitudCancelaOtros() {
        }
        
        public SolicitudCancelaOtros(string RFCEmisor, string RFCReceptor, string Token, long TransaccionID, System.Guid UUID) {
            this.RFCEmisor = RFCEmisor;
            this.RFCReceptor = RFCReceptor;
            this.Token = Token;
            this.TransaccionID = TransaccionID;
            this.UUID = UUID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RespuestaCancelaOtros", WrapperNamespace="http://Ecodex.WS.Model/2011/CFDI", IsWrapped=true)]
    public partial class RespuestaCancelaOtros {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=0)]
        public EcodexIntegrationSample.SrvCancelacion.ListaResultadoCancelacion Resultado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=1)]
        public long TransaccionID;
        
        public RespuestaCancelaOtros() {
        }
        
        public RespuestaCancelaOtros(EcodexIntegrationSample.SrvCancelacion.ListaResultadoCancelacion Resultado, long TransaccionID) {
            this.Resultado = Resultado;
            this.TransaccionID = TransaccionID;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CancelacionesChannel : EcodexIntegrationSample.SrvCancelacion.Cancelaciones, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CancelacionesClient : System.ServiceModel.ClientBase<EcodexIntegrationSample.SrvCancelacion.Cancelaciones>, EcodexIntegrationSample.SrvCancelacion.Cancelaciones {
        
        public CancelacionesClient() {
        }
        
        public CancelacionesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CancelacionesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CancelacionesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CancelacionesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EcodexIntegrationSample.SrvCancelacion.RespuestaCancelaMultiple EcodexIntegrationSample.SrvCancelacion.Cancelaciones.CancelaMultiple(EcodexIntegrationSample.SrvCancelacion.SolicitudCancelaMultiple request) {
            return base.Channel.CancelaMultiple(request);
        }
        
        public EcodexIntegrationSample.SrvCancelacion.ListaResultadoCancelacion CancelaMultiple(EcodexIntegrationSample.SrvCancelacion.ListaCancelar ListaCancelar, string RFC, string Token, long TransaccionID, out string TransaccionID1) {
            EcodexIntegrationSample.SrvCancelacion.SolicitudCancelaMultiple inValue = new EcodexIntegrationSample.SrvCancelacion.SolicitudCancelaMultiple();
            inValue.ListaCancelar = ListaCancelar;
            inValue.RFC = RFC;
            inValue.Token = Token;
            inValue.TransaccionID = TransaccionID;
            EcodexIntegrationSample.SrvCancelacion.RespuestaCancelaMultiple retVal = ((EcodexIntegrationSample.SrvCancelacion.Cancelaciones)(this)).CancelaMultiple(inValue);
            TransaccionID1 = retVal.TransaccionID;
            return retVal.Resultado;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EcodexIntegrationSample.SrvCancelacion.RespuestaRecuperarAcuse EcodexIntegrationSample.SrvCancelacion.Cancelaciones.RecuperarAcuses(EcodexIntegrationSample.SrvCancelacion.SolicitudAcuse request) {
            return base.Channel.RecuperarAcuses(request);
        }
        
        public string RecuperarAcuses(string RFC, string Token, ref long TransaccionID, System.Guid UUID, out string Estatus) {
            EcodexIntegrationSample.SrvCancelacion.SolicitudAcuse inValue = new EcodexIntegrationSample.SrvCancelacion.SolicitudAcuse();
            inValue.RFC = RFC;
            inValue.Token = Token;
            inValue.TransaccionID = TransaccionID;
            inValue.UUID = UUID;
            EcodexIntegrationSample.SrvCancelacion.RespuestaRecuperarAcuse retVal = ((EcodexIntegrationSample.SrvCancelacion.Cancelaciones)(this)).RecuperarAcuses(inValue);
            Estatus = retVal.Estatus;
            TransaccionID = retVal.TransaccionID;
            return retVal.AcuseXML;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EcodexIntegrationSample.SrvCancelacion.RespuestaCancelaOtros EcodexIntegrationSample.SrvCancelacion.Cancelaciones.CancelaOtros(EcodexIntegrationSample.SrvCancelacion.SolicitudCancelaOtros request) {
            return base.Channel.CancelaOtros(request);
        }
        
        public EcodexIntegrationSample.SrvCancelacion.ListaResultadoCancelacion CancelaOtros(string RFCEmisor, string RFCReceptor, string Token, ref long TransaccionID, System.Guid UUID) {
            EcodexIntegrationSample.SrvCancelacion.SolicitudCancelaOtros inValue = new EcodexIntegrationSample.SrvCancelacion.SolicitudCancelaOtros();
            inValue.RFCEmisor = RFCEmisor;
            inValue.RFCReceptor = RFCReceptor;
            inValue.Token = Token;
            inValue.TransaccionID = TransaccionID;
            inValue.UUID = UUID;
            EcodexIntegrationSample.SrvCancelacion.RespuestaCancelaOtros retVal = ((EcodexIntegrationSample.SrvCancelacion.Cancelaciones)(this)).CancelaOtros(inValue);
            TransaccionID = retVal.TransaccionID;
            return retVal.Resultado;
        }
    }
}
