//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcodexIntegrationSample.SrvClients {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="Avisos", Namespace="http://Ecodex.WS.Model/2011/CFDI", ItemName="Aviso")]
    [System.SerializableAttribute()]
    public class Avisos : System.Collections.Generic.List<EcodexIntegrationSample.SrvClients.Aviso> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Aviso", Namespace="http://Ecodex.WS.Model/2011/CFDI")]
    [System.SerializableAttribute()]
    public partial class Aviso : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime VigenciaField;
        
        private string MensajeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Vigencia {
            get {
                return this.VigenciaField;
            }
            set {
                if ((this.VigenciaField.Equals(value) != true)) {
                    this.VigenciaField = value;
                    this.RaisePropertyChanged("Vigencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FallaSesion", Namespace="http://Ecodex.WS.Model/2011/CFDI")]
    [System.SerializableAttribute()]
    public partial class FallaSesion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string RFCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EstatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string RFC {
            get {
                return this.RFCField;
            }
            set {
                if ((object.ReferenceEquals(this.RFCField, value) != true)) {
                    this.RFCField = value;
                    this.RaisePropertyChanged("RFC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int Estatus {
            get {
                return this.EstatusField;
            }
            set {
                if ((this.EstatusField.Equals(value) != true)) {
                    this.EstatusField = value;
                    this.RaisePropertyChanged("Estatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FallaServicio", Namespace="http://Ecodex.WS.Model/2011/CFDI")]
    [System.SerializableAttribute()]
    public partial class FallaServicio : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string RFCField;
        
        private int NumeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EventoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string RFC {
            get {
                return this.RFCField;
            }
            set {
                if ((object.ReferenceEquals(this.RFCField, value) != true)) {
                    this.RFCField = value;
                    this.RaisePropertyChanged("RFC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int Numero {
            get {
                return this.NumeroField;
            }
            set {
                if ((this.NumeroField.Equals(value) != true)) {
                    this.NumeroField = value;
                    this.RaisePropertyChanged("Numero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string Evento {
            get {
                return this.EventoField;
            }
            set {
                if ((object.ReferenceEquals(this.EventoField, value) != true)) {
                    this.EventoField = value;
                    this.RaisePropertyChanged("Evento");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CuentaEstatus", Namespace="http://Ecodex.WS.Model/2011/CFDI")]
    [System.SerializableAttribute()]
    public partial class CuentaEstatus : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RFCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaInicioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaFinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TimbresAsignadosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TimbresDisponiblesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] CertificadosField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RFC {
            get {
                return this.RFCField;
            }
            set {
                if ((object.ReferenceEquals(this.RFCField, value) != true)) {
                    this.RFCField = value;
                    this.RaisePropertyChanged("RFC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.DateTime FechaInicio {
            get {
                return this.FechaInicioField;
            }
            set {
                if ((this.FechaInicioField.Equals(value) != true)) {
                    this.FechaInicioField = value;
                    this.RaisePropertyChanged("FechaInicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.DateTime FechaFin {
            get {
                return this.FechaFinField;
            }
            set {
                if ((this.FechaFinField.Equals(value) != true)) {
                    this.FechaFinField = value;
                    this.RaisePropertyChanged("FechaFin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int TimbresAsignados {
            get {
                return this.TimbresAsignadosField;
            }
            set {
                if ((this.TimbresAsignadosField.Equals(value) != true)) {
                    this.TimbresAsignadosField = value;
                    this.RaisePropertyChanged("TimbresAsignados");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int TimbresDisponibles {
            get {
                return this.TimbresDisponiblesField;
            }
            set {
                if ((this.TimbresDisponiblesField.Equals(value) != true)) {
                    this.TimbresDisponiblesField = value;
                    this.RaisePropertyChanged("TimbresDisponibles");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string[] Certificados {
            get {
                return this.CertificadosField;
            }
            set {
                if ((object.ReferenceEquals(this.CertificadosField, value) != true)) {
                    this.CertificadosField = value;
                    this.RaisePropertyChanged("Certificados");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AltaEmisor", Namespace="http://Ecodex.WS.Model/2011/CFDI")]
    [System.SerializableAttribute()]
    public partial class AltaEmisor : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RFCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RazonSocialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoElectronicoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RFC {
            get {
                return this.RFCField;
            }
            set {
                if ((object.ReferenceEquals(this.RFCField, value) != true)) {
                    this.RFCField = value;
                    this.RaisePropertyChanged("RFC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RazonSocial {
            get {
                return this.RazonSocialField;
            }
            set {
                if ((object.ReferenceEquals(this.RazonSocialField, value) != true)) {
                    this.RazonSocialField = value;
                    this.RaisePropertyChanged("RazonSocial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string CorreoElectronico {
            get {
                return this.CorreoElectronicoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoElectronicoField, value) != true)) {
                    this.CorreoElectronicoField = value;
                    this.RaisePropertyChanged("CorreoElectronico");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultadoRegistroEmisor", Namespace="http://Ecodex.WS.Model/2011/CFDI")]
    [System.SerializableAttribute()]
    public partial class ResultadoRegistroEmisor : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RFCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClaveCertificadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RFC {
            get {
                return this.RFCField;
            }
            set {
                if ((object.ReferenceEquals(this.RFCField, value) != true)) {
                    this.RFCField = value;
                    this.RaisePropertyChanged("RFC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string Estatus {
            get {
                return this.EstatusField;
            }
            set {
                if ((object.ReferenceEquals(this.EstatusField, value) != true)) {
                    this.EstatusField = value;
                    this.RaisePropertyChanged("Estatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string ClaveCertificado {
            get {
                return this.ClaveCertificadoField;
            }
            set {
                if ((object.ReferenceEquals(this.ClaveCertificadoField, value) != true)) {
                    this.ClaveCertificadoField = value;
                    this.RaisePropertyChanged("ClaveCertificado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FallaValidacion", Namespace="http://Ecodex.WS.Model/2011/CFDI")]
    [System.SerializableAttribute()]
    public partial class FallaValidacion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string RFCField;
        
        private int NumeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NodoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AntecedenteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SugerenciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EventoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string RFC {
            get {
                return this.RFCField;
            }
            set {
                if ((object.ReferenceEquals(this.RFCField, value) != true)) {
                    this.RFCField = value;
                    this.RaisePropertyChanged("RFC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int Numero {
            get {
                return this.NumeroField;
            }
            set {
                if ((this.NumeroField.Equals(value) != true)) {
                    this.NumeroField = value;
                    this.RaisePropertyChanged("Numero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string Nodo {
            get {
                return this.NodoField;
            }
            set {
                if ((object.ReferenceEquals(this.NodoField, value) != true)) {
                    this.NodoField = value;
                    this.RaisePropertyChanged("Nodo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string Antecedente {
            get {
                return this.AntecedenteField;
            }
            set {
                if ((object.ReferenceEquals(this.AntecedenteField, value) != true)) {
                    this.AntecedenteField = value;
                    this.RaisePropertyChanged("Antecedente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string Sugerencia {
            get {
                return this.SugerenciaField;
            }
            set {
                if ((object.ReferenceEquals(this.SugerenciaField, value) != true)) {
                    this.SugerenciaField = value;
                    this.RaisePropertyChanged("Sugerencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string Evento {
            get {
                return this.EventoField;
            }
            set {
                if ((object.ReferenceEquals(this.EventoField, value) != true)) {
                    this.EventoField = value;
                    this.RaisePropertyChanged("Evento");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", ConfigurationName="SrvClients.Clientes")]
    public interface Clientes {
        
        // CODEGEN: Generating message contract since the wrapper name (SolicitudAvisosNuevos) of message SolicitudAvisosNuevos does not match the default value (AvisosNuevos)
        [System.ServiceModel.OperationContractAttribute(Action="http://Ecodex.WS.Model/2011/CFDI/ServicioClientes/AvisosNuevos", ReplyAction="http://Ecodex.WS.Model/2011/CFDI/Clientes/AvisosNuevosResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EcodexIntegrationSample.SrvClients.FallaSesion), Action="http://Ecodex.WS.Model/2011/CFDI/Clientes/AvisosNuevosFallaSesionFault", Name="FallaSesion")]
        [System.ServiceModel.FaultContractAttribute(typeof(EcodexIntegrationSample.SrvClients.FallaServicio), Action="http://Ecodex.WS.Model/2011/CFDI/Clientes/AvisosNuevosFallaServicioFault", Name="FallaServicio")]
        EcodexIntegrationSample.SrvClients.RespuestaAvisosNuevos AvisosNuevos(EcodexIntegrationSample.SrvClients.SolicitudAvisosNuevos request);
        
        // CODEGEN: Generating message contract since the wrapper name (SolicitudEstatusCuenta) of message SolicitudEstatusCuenta does not match the default value (EstatusCuenta)
        [System.ServiceModel.OperationContractAttribute(Action="http://Ecodex.WS.Model/2011/CFDI/ServicioClientes/EstatusCuenta", ReplyAction="http://Ecodex.WS.Model/2011/CFDI/Clientes/EstatusCuentaResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EcodexIntegrationSample.SrvClients.FallaServicio), Action="http://Ecodex.WS.Model/2011/CFDI/Clientes/EstatusCuentaFallaServicioFault", Name="FallaServicio")]
        [System.ServiceModel.FaultContractAttribute(typeof(EcodexIntegrationSample.SrvClients.FallaSesion), Action="http://Ecodex.WS.Model/2011/CFDI/Clientes/EstatusCuentaFallaSesionFault", Name="FallaSesion")]
        EcodexIntegrationSample.SrvClients.RespuestaEstatusCuenta EstatusCuenta(EcodexIntegrationSample.SrvClients.SolicitudEstatusCuenta request);
        
        // CODEGEN: Generating message contract since the wrapper name (SolicitudRegistroCliente) of message SolicitudRegistroCliente does not match the default value (Registrar)
        [System.ServiceModel.OperationContractAttribute(Action="Registrar", ReplyAction="http://Ecodex.WS.Model/2011/CFDI/Clientes/RegistrarResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EcodexIntegrationSample.SrvClients.FallaSesion), Action="http://Ecodex.WS.Model/2011/CFDI/Clientes/RegistrarFallaSesionFault", Name="FallaSesion")]
        [System.ServiceModel.FaultContractAttribute(typeof(EcodexIntegrationSample.SrvClients.FallaValidacion), Action="http://Ecodex.WS.Model/2011/CFDI/Clientes/RegistrarFallaValidacionFault", Name="FallaValidacion")]
        [System.ServiceModel.FaultContractAttribute(typeof(EcodexIntegrationSample.SrvClients.FallaServicio), Action="http://Ecodex.WS.Model/2011/CFDI/Clientes/RegistrarFallaServicioFault", Name="FallaServicio")]
        EcodexIntegrationSample.SrvClients.RespuestaRegistro Registrar(EcodexIntegrationSample.SrvClients.SolicitudRegistroCliente request);
        
        // CODEGEN: Generating message contract since the wrapper name (SolicitudAsignacionTimbres) of message SolicitudAsignacionTimbres does not match the default value (AsignacionTimbres)
        [System.ServiceModel.OperationContractAttribute(Action="AsignacionTimbres", ReplyAction="http://Ecodex.WS.Model/2011/CFDI/Clientes/AsignacionTimbresResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EcodexIntegrationSample.SrvClients.FallaServicio), Action="http://Ecodex.WS.Model/2011/CFDI/Clientes/AsignacionTimbresFallaServicioFault", Name="FallaServicio")]
        [System.ServiceModel.FaultContractAttribute(typeof(EcodexIntegrationSample.SrvClients.FallaValidacion), Action="http://Ecodex.WS.Model/2011/CFDI/Clientes/AsignacionTimbresFallaValidacionFault", Name="FallaValidacion")]
        [System.ServiceModel.FaultContractAttribute(typeof(EcodexIntegrationSample.SrvClients.FallaSesion), Action="http://Ecodex.WS.Model/2011/CFDI/Clientes/AsignacionTimbresFallaSesionFault", Name="FallaSesion")]
        EcodexIntegrationSample.SrvClients.RespuestaAsignacionTimbres AsignacionTimbres(EcodexIntegrationSample.SrvClients.SolicitudAsignacionTimbres request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SolicitudAvisosNuevos", WrapperNamespace="http://Ecodex.WS.Model/2011/CFDI", IsWrapped=true)]
    public partial class SolicitudAvisosNuevos {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=0)]
        public string RFC;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=1)]
        public string Token;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=2)]
        public long TransaccionID;
        
        public SolicitudAvisosNuevos() {
        }
        
        public SolicitudAvisosNuevos(string RFC, string Token, long TransaccionID) {
            this.RFC = RFC;
            this.Token = Token;
            this.TransaccionID = TransaccionID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RespuestaAvisosNuevos", WrapperNamespace="http://Ecodex.WS.Model/2011/CFDI", IsWrapped=true)]
    public partial class RespuestaAvisosNuevos {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=0)]
        public EcodexIntegrationSample.SrvClients.Avisos Avisos;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=1)]
        public long TransaccionID;
        
        public RespuestaAvisosNuevos() {
        }
        
        public RespuestaAvisosNuevos(EcodexIntegrationSample.SrvClients.Avisos Avisos, long TransaccionID) {
            this.Avisos = Avisos;
            this.TransaccionID = TransaccionID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SolicitudEstatusCuenta", WrapperNamespace="http://Ecodex.WS.Model/2011/CFDI", IsWrapped=true)]
    public partial class SolicitudEstatusCuenta {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=0)]
        public string RFC;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=1)]
        public string Token;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=2)]
        public long TransaccionID;
        
        public SolicitudEstatusCuenta() {
        }
        
        public SolicitudEstatusCuenta(string RFC, string Token, long TransaccionID) {
            this.RFC = RFC;
            this.Token = Token;
            this.TransaccionID = TransaccionID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RespuestaEstatusCuenta", WrapperNamespace="http://Ecodex.WS.Model/2011/CFDI", IsWrapped=true)]
    public partial class RespuestaEstatusCuenta {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=0)]
        public EcodexIntegrationSample.SrvClients.CuentaEstatus Estatus;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=1)]
        public long TransaccionID;
        
        public RespuestaEstatusCuenta() {
        }
        
        public RespuestaEstatusCuenta(EcodexIntegrationSample.SrvClients.CuentaEstatus Estatus, long TransaccionID) {
            this.Estatus = Estatus;
            this.TransaccionID = TransaccionID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SolicitudRegistroCliente", WrapperNamespace="http://Ecodex.WS.Model/2011/CFDI", IsWrapped=true)]
    public partial class SolicitudRegistroCliente {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=0)]
        public EcodexIntegrationSample.SrvClients.AltaEmisor Emisor;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=1)]
        public string RfcIntegrador;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=2)]
        public string Token;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=3)]
        public long TransaccionID;
        
        public SolicitudRegistroCliente() {
        }
        
        public SolicitudRegistroCliente(EcodexIntegrationSample.SrvClients.AltaEmisor Emisor, string RfcIntegrador, string Token, long TransaccionID) {
            this.Emisor = Emisor;
            this.RfcIntegrador = RfcIntegrador;
            this.Token = Token;
            this.TransaccionID = TransaccionID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RespuestaRegistro", WrapperNamespace="http://Ecodex.WS.Model/2011/CFDI", IsWrapped=true)]
    public partial class RespuestaRegistro {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=0)]
        public EcodexIntegrationSample.SrvClients.ResultadoRegistroEmisor Respuesta;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=1)]
        public long TransaccionId;
        
        public RespuestaRegistro() {
        }
        
        public RespuestaRegistro(EcodexIntegrationSample.SrvClients.ResultadoRegistroEmisor Respuesta, long TransaccionId) {
            this.Respuesta = Respuesta;
            this.TransaccionId = TransaccionId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SolicitudAsignacionTimbres", WrapperNamespace="http://Ecodex.WS.Model/2011/CFDI", IsWrapped=true)]
    public partial class SolicitudAsignacionTimbres {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=0)]
        public string RFC;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=1)]
        public int TimbresAsignar;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=2)]
        public string Token;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=3)]
        public long TransaccionId;
        
        public SolicitudAsignacionTimbres() {
        }
        
        public SolicitudAsignacionTimbres(string RFC, int TimbresAsignar, string Token, long TransaccionId) {
            this.RFC = RFC;
            this.TimbresAsignar = TimbresAsignar;
            this.Token = Token;
            this.TransaccionId = TransaccionId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RespuestaAsignacionTimbres", WrapperNamespace="http://Ecodex.WS.Model/2011/CFDI", IsWrapped=true)]
    public partial class RespuestaAsignacionTimbres {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=0)]
        public long SaldoAnterior;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=1)]
        public int SaldoNuevo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=2)]
        public string Token;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=3)]
        public long TransaccionId;
        
        public RespuestaAsignacionTimbres() {
        }
        
        public RespuestaAsignacionTimbres(long SaldoAnterior, int SaldoNuevo, string Token, long TransaccionId) {
            this.SaldoAnterior = SaldoAnterior;
            this.SaldoNuevo = SaldoNuevo;
            this.Token = Token;
            this.TransaccionId = TransaccionId;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ClientesChannel : EcodexIntegrationSample.SrvClients.Clientes, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClientesClient : System.ServiceModel.ClientBase<EcodexIntegrationSample.SrvClients.Clientes>, EcodexIntegrationSample.SrvClients.Clientes {
        
        public ClientesClient() {
        }
        
        public ClientesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClientesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClientesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClientesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EcodexIntegrationSample.SrvClients.RespuestaAvisosNuevos EcodexIntegrationSample.SrvClients.Clientes.AvisosNuevos(EcodexIntegrationSample.SrvClients.SolicitudAvisosNuevos request) {
            return base.Channel.AvisosNuevos(request);
        }
        
        public EcodexIntegrationSample.SrvClients.Avisos AvisosNuevos(string RFC, string Token, ref long TransaccionID) {
            EcodexIntegrationSample.SrvClients.SolicitudAvisosNuevos inValue = new EcodexIntegrationSample.SrvClients.SolicitudAvisosNuevos();
            inValue.RFC = RFC;
            inValue.Token = Token;
            inValue.TransaccionID = TransaccionID;
            EcodexIntegrationSample.SrvClients.RespuestaAvisosNuevos retVal = ((EcodexIntegrationSample.SrvClients.Clientes)(this)).AvisosNuevos(inValue);
            TransaccionID = retVal.TransaccionID;
            return retVal.Avisos;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EcodexIntegrationSample.SrvClients.RespuestaEstatusCuenta EcodexIntegrationSample.SrvClients.Clientes.EstatusCuenta(EcodexIntegrationSample.SrvClients.SolicitudEstatusCuenta request) {
            return base.Channel.EstatusCuenta(request);
        }
        
        public EcodexIntegrationSample.SrvClients.CuentaEstatus EstatusCuenta(string RFC, string Token, ref long TransaccionID) {
            EcodexIntegrationSample.SrvClients.SolicitudEstatusCuenta inValue = new EcodexIntegrationSample.SrvClients.SolicitudEstatusCuenta();
            inValue.RFC = RFC;
            inValue.Token = Token;
            inValue.TransaccionID = TransaccionID;
            EcodexIntegrationSample.SrvClients.RespuestaEstatusCuenta retVal = ((EcodexIntegrationSample.SrvClients.Clientes)(this)).EstatusCuenta(inValue);
            TransaccionID = retVal.TransaccionID;
            return retVal.Estatus;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EcodexIntegrationSample.SrvClients.RespuestaRegistro EcodexIntegrationSample.SrvClients.Clientes.Registrar(EcodexIntegrationSample.SrvClients.SolicitudRegistroCliente request) {
            return base.Channel.Registrar(request);
        }
        
        public EcodexIntegrationSample.SrvClients.ResultadoRegistroEmisor Registrar(EcodexIntegrationSample.SrvClients.AltaEmisor Emisor, string RfcIntegrador, string Token, long TransaccionID, out long TransaccionId1) {
            EcodexIntegrationSample.SrvClients.SolicitudRegistroCliente inValue = new EcodexIntegrationSample.SrvClients.SolicitudRegistroCliente();
            inValue.Emisor = Emisor;
            inValue.RfcIntegrador = RfcIntegrador;
            inValue.Token = Token;
            inValue.TransaccionID = TransaccionID;
            EcodexIntegrationSample.SrvClients.RespuestaRegistro retVal = ((EcodexIntegrationSample.SrvClients.Clientes)(this)).Registrar(inValue);
            TransaccionId1 = retVal.TransaccionId;
            return retVal.Respuesta;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EcodexIntegrationSample.SrvClients.RespuestaAsignacionTimbres EcodexIntegrationSample.SrvClients.Clientes.AsignacionTimbres(EcodexIntegrationSample.SrvClients.SolicitudAsignacionTimbres request) {
            return base.Channel.AsignacionTimbres(request);
        }
        
        public long AsignacionTimbres(string RFC, int TimbresAsignar, ref string Token, ref long TransaccionId, out int SaldoNuevo) {
            EcodexIntegrationSample.SrvClients.SolicitudAsignacionTimbres inValue = new EcodexIntegrationSample.SrvClients.SolicitudAsignacionTimbres();
            inValue.RFC = RFC;
            inValue.TimbresAsignar = TimbresAsignar;
            inValue.Token = Token;
            inValue.TransaccionId = TransaccionId;
            EcodexIntegrationSample.SrvClients.RespuestaAsignacionTimbres retVal = ((EcodexIntegrationSample.SrvClients.Clientes)(this)).AsignacionTimbres(inValue);
            SaldoNuevo = retVal.SaldoNuevo;
            Token = retVal.Token;
            TransaccionId = retVal.TransaccionId;
            return retVal.SaldoAnterior;
        }
    }
}
